### ISSUE TITLE
consular init error in Ruby 1.9.3-p194

### ISSUE THREAD

**Issue by jannisg** [achiurizo/consular-osx#5]
I've been trying to get the `consular-osx` core working on my MacBook Air but am not having any luck so far and am consistently seeing the following error message when trying to run `consular init` after installing both `consular` and `consular-osx`.

I am running `ruby-1.9.3-p194` via RVM on a mid-2012, 10.8.1 MacBook Air in case this might factor in.

Here is the error which is printed to my console `Terminal.app` using `zsh`.

```
Jannis-MacBook-Air: ~                                                                                                                                  
→ consular init
/Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/rb-appscript-0.6.1/lib/ae.bundle: [BUG] Segmentation fault
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin12.0.0]

-- Control frame information -----------------------------------------------
c:0029 p:-17538451360810 s:0100 b:0100 l:000099 d:000099 TOP   
c:0028 p:---- s:0098 b:0098 l:000097 d:000097 CFUNC  :require
c:0027 p:0036 s:0094 b:0094 l:000093 d:000093 METHOD /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36
c:0026 p:0013 s:0087 b:0087 l:000086 d:000086 CLASS  /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/rb-appscript-0.6.1/lib/_aem/mactypes.rb:12
c:0025 p:0009 s:0085 b:0085 l:000084 d:000084 TOP    /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/rb-appscript-0.6.1/lib/_aem/mactypes.rb:7
c:0024 p:---- s:0083 b:0083 l:000082 d:000082 FINISH
c:0023 p:---- s:0081 b:0081 l:000080 d:000080 CFUNC  :require
c:0022 p:0036 s:0077 b:0077 l:000076 d:000076 METHOD /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36
c:0021 p:0011 s:0070 b:0070 l:000069 d:000069 TOP    /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/rb-appscript-0.6.1/lib/appscript.rb:8
c:0020 p:---- s:0068 b:0068 l:000067 d:000067 FINISH
c:0019 p:---- s:0066 b:0066 l:000065 d:000065 CFUNC  :require
c:0018 p:0036 s:0062 b:0062 l:000061 d:000061 METHOD /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36
c:0017 p:0023 s:0055 b:0055 l:000054 d:000054 TOP    /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/consular-osx-1.0.1/lib/consular/osx.rb:2
c:0016 p:---- s:0053 b:0053 l:000052 d:000052 FINISH
c:0015 p:---- s:0051 b:0051 l:000050 d:000050 CFUNC  :require
c:0014 p:0089 s:0047 b:0047 l:000043 d:000046 BLOCK  /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60
c:0013 p:0158 s:0044 b:0044 l:000043 d:000043 METHOD /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35
c:0012 p:0011 s:0037 b:0037 l:000026 d:000036 EVAL   /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/consular-1.0.2/bin/consular:11
c:0011 p:---- s:0035 b:0035 l:000034 d:000034 FINISH
c:0010 p:---- s:0033 b:0033 l:000032 d:000032 CFUNC  :instance_eval
c:0009 p:0104 s:0027 b:0027 l:000026 d:000026 TOP    /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/consular-1.0.2/bin/consular:10
c:0008 p:---- s:0024 b:0024 l:000023 d:000023 FINISH
c:0007 p:---- s:0022 b:0022 l:000021 d:000021 CFUNC  :load
c:0006 p:0127 s:0018 b:0018 l:000d18 d:000c30 EVAL   /Users/jannis/.rvm/gems/ruby-1.9.3-p194/bin/consular:19
c:0005 p:---- s:0015 b:0015 l:000014 d:000014 FINISH
c:0004 p:---- s:0013 b:0013 l:000012 d:000012 CFUNC  :eval
c:0003 p:0101 s:0007 b:0007 l:000d18 d:002490 EVAL   /Users/jannis/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:0000 s:0002 b:0002 l:000d18 d:000d18 TOP   

-- Ruby level backtrace information ----------------------------------------
/Users/jannis/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'
/Users/jannis/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
/Users/jannis/.rvm/gems/ruby-1.9.3-p194/bin/consular:19:in `<main>'
/Users/jannis/.rvm/gems/ruby-1.9.3-p194/bin/consular:19:in `load'
/Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/consular-1.0.2/bin/consular:10:in `<top (required)>'
/Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/consular-1.0.2/bin/consular:10:in `instance_eval'
/Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/consular-1.0.2/bin/consular:11:in `<top (required)>'
/Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
/Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
/Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
/Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/consular-osx-1.0.1/lib/consular/osx.rb:2:in `<top (required)>'
/Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/rb-appscript-0.6.1/lib/appscript.rb:8:in `<top (required)>'
/Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/rb-appscript-0.6.1/lib/_aem/mactypes.rb:7:in `<top (required)>'
/Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/rb-appscript-0.6.1/lib/_aem/mactypes.rb:12:in `<module:MacTypes>'
/Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'

-- C level backtrace information -------------------------------------------

   See Crash Report log file under ~/Library/Logs/CrashReporter or
   /Library/Logs/CrashReporter, for the more detail of.

-- Other runtime information -----------------------------------------------

* Loaded script: /Users/jannis/.rvm/gems/ruby-1.9.3-p194/bin/consular

* Loaded features:

    0 enumerator.so
    1 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/x86_64-darwin12.0.0/enc/encdb.bundle
    2 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/x86_64-darwin12.0.0/enc/trans/transdb.bundle
    3 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/defaults.rb
    4 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/x86_64-darwin12.0.0/rbconfig.rb
    5 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/deprecate.rb
    6 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/exceptions.rb
    7 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb
    8 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems.rb
    9 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/version.rb
   10 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/requirement.rb
   11 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/platform.rb
   12 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb
   13 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/path_support.rb
   14 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb
   15 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/x86_64-darwin12.0.0/etc.bundle
   16 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/fileutils.rb
   17 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/x86_64-darwin12.0.0/pathname.bundle
   18 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/pathname.rb
   19 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.1/lib/bundler/gem_path_manipulation.rb
   20 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/syntax_error.rb
   21 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/x86_64-darwin12.0.0/psych.bundle
   22 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/x86_64-darwin12.0.0/stringio.bundle
   23 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/nodes/node.rb
   24 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/nodes/stream.rb
   25 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/nodes/document.rb
   26 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/nodes/sequence.rb
   27 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/nodes/scalar.rb
   28 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/nodes/mapping.rb
   29 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/nodes/alias.rb
   30 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/nodes.rb
   31 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/streaming.rb
   32 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/visitors/visitor.rb
   33 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/x86_64-darwin12.0.0/strscan.bundle
   34 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/scalar_scanner.rb
   35 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/visitors/to_ruby.rb
   36 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/visitors/emitter.rb
   37 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb
   38 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/json/ruby_events.rb
   39 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/visitors/json_tree.rb
   40 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/visitors/depth_first.rb
   41 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/visitors.rb
   42 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/handler.rb
   43 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/tree_builder.rb
   44 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/parser.rb
   45 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/omap.rb
   46 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/set.rb
   47 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/coder.rb
   48 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/core_ext.rb
   49 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/x86_64-darwin12.0.0/date_core.bundle
   50 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/date/format.rb
   51 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/date.rb
   52 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/deprecated.rb
   53 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/stream.rb
   54 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/json/yaml_events.rb
   55 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/json/tree_builder.rb
   56 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/json/stream.rb
   57 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych/handlers/document_stream.rb
   58 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych.rb
   59 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/yaml.rb
   60 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.1/lib/bundler/psyched_yaml.rb
   61 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.1/lib/bundler/gem_helpers.rb
   62 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.1/lib/bundler/match_platform.rb
   63 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.1/lib/bundler/rubygems_ext.rb
   64 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/config_file.rb
   65 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/psych_additions.rb
   66 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/psych_tree.rb
   67 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/syck_hack.rb
   68 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.1/lib/bundler/rubygems_integration.rb
   69 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.1/lib/bundler/version.rb
   70 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.1/lib/bundler.rb
   71 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/rubygems-bundler-1.1.0/lib/rubygems-bundler/noexec.rb
   72 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/consular-1.0.2/lib/consular/version.rb
   73 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/consular-1.0.2/lib/consular/core.rb
   74 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.8/lib/active_support/ordered_hash.rb
   75 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.8/lib/active_support/core_ext/array/extract_options.rb
   76 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/consular-1.0.2/lib/consular/dsl.rb
   77 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/core_ext/hash_with_indifferent_access.rb
   78 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/core_ext/ordered_hash.rb
   79 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/error.rb
   80 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/shell.rb
   81 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/invocation.rb
   82 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/parser/argument.rb
   83 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/parser/arguments.rb
   84 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/parser/option.rb
   85 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/parser/options.rb
   86 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/parser.rb
   87 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/task.rb
   88 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/util.rb
   89 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/base.rb
   90 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor.rb
   91 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/uri/common.rb
   92 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/uri/generic.rb
   93 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/uri/ftp.rb
   94 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/uri/http.rb
   95 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/uri/https.rb
   96 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/uri/ldap.rb
   97 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/uri/ldaps.rb
   98 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/uri/mailto.rb
   99 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/uri.rb
  100 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/core_ext/file_binary_read.rb
  101 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/actions/empty_directory.rb
  102 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/actions/create_file.rb
  103 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/actions/create_link.rb
  104 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/actions/directory.rb
  105 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/erb.rb
  106 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/time.rb
  107 /Users/jannis/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/open-uri.rb
  108 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/actions/file_manipulation.rb
  109 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/actions/inject_into_file.rb
  110 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/actions.rb
  111 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/consular-1.0.2/lib/consular/cli.rb
  112 /Users/jannis/.rvm/gems/ruby-1.9.3-p194/gems/consular-1.0.2/lib/consular.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

[1]    83929 abort      consular init
```

Any ideas on what might have gone wrong would be much appreciated.

Thanks for reading.

**Comment by achiurizo** [comment]
This probably has to relate to the fact `rb-appscript` is no longer maintained and its becoming increasingly hard to get working on later os versions (see #1). I'm debating on just leveraging Macruby instead and see how that fairs.

**Comment by jannisg** [comment]
@achiu That's certainly a possibility. I will try installing the `rb-appscript` gem manually tomorrow on the laptop and see if that makes a difference. Oddly enough my Mac Pro also running 10.8.2 and ruby-1.9.3-p194 is running Consular just fine without any errors whatsoever.

**Comment by jannisg** [comment]
Hmm… this one is a bit odd. I've reinstalled `rb-appscript`, `consular` and `consular-osx` into a new `rvm` gemset and now things are working just fine.

Sorry for taking up your time with something that is clearly my system/rvm config issue and not this project's fault. Thanks again for the response though, much appreciated.

**Comment by achiurizo** [comment]
No problem, thanks for the report!
